version: "3"
services:
  devcontainer:
    network_mode: "host"
    container_name: sip2rtsp-devcontainer
    shm_size: "256mb"
    build:
      context: .
      target: devcontainer
      args:
        PULSEGST_IMAGE: ghcr.io/nanosonde/pulsegst:main-fe22165
    volumes:
      - .:/workspace/sip2rtsp:cached
      - /etc/localtime:/etc/localtime:ro
      - ./config/config.yml:/config/config.yml:ro
